name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on:
  workflow_dispatch:
  push:
    branches:
    - master
    # Just in case I ever change the branch name or something
    - main
    - release

env:
  INTERNAL_NAME: TinyCmds
  CONFIGURATION: Release
  PERSONAL_PLUGIN_REPO: PrincessRTFM/MyDalamudPlugins
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
    - name: Restore
      run: dotnet restore -r win
    - name: Build
      run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: ${{ env.INTERNAL_NAME }}/bin/${{ env.CONFIGURATION }}/${{ env.INTERNAL_NAME }}
        if-no-files-found: error
        retention-days: 1
    - name: Tag
      run: |
        buildVersion=$(jq -j .AssemblyVersion "${{ env.INTERNAL_NAME }}/bin/${{ env.CONFIGURATION }}/${{ env.INTERNAL_NAME }}/${{ env.INTERNAL_NAME }}.json")
        git tag -am "[Automated build $buildVersion]" "v$buildVersion"
        git push origin "v$buildVersion"
      shell: bash
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_COMMITTER_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        repository: ${{ env.PERSONAL_PLUGIN_REPO }}
        token: ${{ secrets.PAT }}
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: PluginRepoZip
        path: plugins/${{ env.INTERNAL_NAME }}
    - name: Commit
      uses: EndBug/add-and-commit@v7
      with:
        add: plugins/
        branch: master
        pathspec_error_handling: exitImmediately
        author_name: GitHub Action
        author_email: github-actions[bot]@users.noreply.github.com
        message: Update ${{ env.INTERNAL_NAME }}
